#!/bin/bash
#
#------------------------------------------------------------------------------#
# Contributor : Javier I. Camacho                                              #
# Case created on :  08-2024                                                   #
#------------------------------------------------------------------------------#
# Repository : https://osf.io/gkubp/?view_only=41f95f9ff8e94a4681c626a112955d50#
# Email           : javier.camacho@brand.lth.se                                #
#------------------------------------------------------------------------------#
cd "${0%/*}" || exit 1                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#-------------------------------------------------------------------------------

#cleanCase0
#rm -rf constant/triSurface
#rm -rf constant/polyMesh
rm -rf log.*
#rm -rf Py*
#rm -rf Gn*

# Manual input for folders to remove
echo "Enter the names of folders to remove inside each processor (space-separated), or leave blank to skip:"
read -r foldersToRemove
for procDir in processor*; do
	if [ -d "$procDir" ]; then
		for folder in $foldersToRemove; do
			target="$procDir/$folder"
			if [ -d "$target" ]; then
				echo "Removing folder: $target"
				rm -rf "$target"
			else
				echo "Folder not found: $target"
			fi
		done
	fi
done
